import { createContext, useContext, useState, useEffect, useCallback, useRef } from 'react';
import toast from 'react-hot-toast';
import { authLogin, authLogout, authCheck, setCsrfToken } from '../services/api.js';

const AuthContext = createContext(null);

export function AuthProvider({ children }) {
  const [authenticated, setAuthenticated] = useState(false);
  const [passwordChangeRequired, setPasswordChangeRequired] = useState(false);
  const [setupRequired, setSetupRequired] = useState(false);
  const [encryptionKeyAutoGenerated, setEncryptionKeyAutoGenerated] = useState(false);
  const [idleTimeoutMinutes, setIdleTimeoutMinutes] = useState(60);
  const [loading, setLoading] = useState(true);
  const csrfRef = useRef(null);
  const idleTimerRef = useRef(null);
  const isAuthRef = useRef(false);

  const doLogout = useCallback(async (reason) => {
    clearTimeout(idleTimerRef.current);
    isAuthRef.current = false;
    try { await authLogout(); } catch { /* ignore */ }
    setAuthenticated(false);
    setPasswordChangeRequired(false);
    setSetupRequired(false);
    setEncryptionKeyAutoGenerated(false);
    if (reason === 'idle') {
      toast.error('You were logged out due to inactivity.', { duration: 6000 });
    }
  }, []);

  // Reset the idle countdown timer
  const resetIdleTimer = useCallback((timeoutMinutes) => {
    clearTimeout(idleTimerRef.current);
    if (!isAuthRef.current) return;
    idleTimerRef.current = setTimeout(() => {
      doLogout('idle');
    }, timeoutMinutes * 60 * 1000);
  }, [doLogout]);

  // Attach/detach activity listeners
  useEffect(() => {
    if (!authenticated) return;
    const events = ['mousemove', 'keydown', 'mousedown', 'touchstart', 'scroll', 'click'];
    const handler = () => resetIdleTimer(idleTimeoutMinutes);
    events.forEach(e => window.addEventListener(e, handler, { passive: true }));
    resetIdleTimer(idleTimeoutMinutes);
    return () => {
      events.forEach(e => window.removeEventListener(e, handler));
      clearTimeout(idleTimerRef.current);
    };
  }, [authenticated, idleTimeoutMinutes, resetIdleTimer]);

  const check = useCallback(async () => {
    try {
      const res = await authCheck();
      const auth = res.data.authenticated;
      isAuthRef.current = auth;
      setAuthenticated(auth);
      setPasswordChangeRequired(res.data.passwordChangeRequired || false);
      setSetupRequired(res.data.setupRequired || false);
      setEncryptionKeyAutoGenerated(res.data.encryptionKeyAutoGenerated || false);
      setIdleTimeoutMinutes(res.data.idleTimeoutMinutes || 60);
      if (res.data.csrfToken) {
        csrfRef.current = res.data.csrfToken;
        setCsrfToken(res.data.csrfToken);
      }
    } catch {
      isAuthRef.current = false;
      setAuthenticated(false);
      setPasswordChangeRequired(false);
      setSetupRequired(false);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    check();
    const handler = () => {
      isAuthRef.current = false;
      setAuthenticated(false);
      setPasswordChangeRequired(false);
      setSetupRequired(false);
      setEncryptionKeyAutoGenerated(false);
    };
    window.addEventListener('auth:logout', handler);
    return () => window.removeEventListener('auth:logout', handler);
  }, [check]);

  const login = async (password) => {
    const res = await authLogin(password);
    if (res.data.success) {
      isAuthRef.current = true;
      setAuthenticated(true);
      await check();
      return true;
    }
    return false;
  };

  const logout = async () => {
    await doLogout('manual');
  };

  const clearPasswordChangeRequired = () => {
    setPasswordChangeRequired(false);
  };

  const completeSetup = (csrfToken) => {
    setCsrfToken(csrfToken);
    isAuthRef.current = true;
    setSetupRequired(false);
    setAuthenticated(true);
    setPasswordChangeRequired(false);
  };

  return (
    <AuthContext.Provider value={{ authenticated, passwordChangeRequired, setupRequired, encryptionKeyAutoGenerated, idleTimeoutMinutes, loading, login, logout, clearPasswordChangeRequired, completeSetup }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error('useAuth must be within AuthProvider');
  return ctx;
}
