import { fileURLToPath } from 'url';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import path from 'path';
import crypto from 'crypto';
import dotenv from 'dotenv';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, '../../../.env') });

const { version } = JSON.parse(
  readFileSync(path.resolve(__dirname, '../../package.json'), 'utf8')
);

// ─── Resolve data directory early (needed for secret files) ──────────────
const dataDir = path.resolve(process.env.DATA_DIR || path.join(__dirname, '../../data'));

// ─── Encryption key — load from env or auto-generate once ────────────────
// If DB_ENCRYPTION_KEY is set it takes precedence.
// Otherwise a 32-byte hex key is generated and persisted in DATA_DIR/encryption.key.
// A prominent warning is logged (and exposed to the UI) in the auto-generated case.
let encryptionKeyAutoGenerated = false;
function resolveEncryptionKey() {
  if (process.env.DB_ENCRYPTION_KEY) {
    if (process.env.DB_ENCRYPTION_KEY.length < 32) {
      console.error('FATAL: DB_ENCRYPTION_KEY must be at least 32 characters. Use: openssl rand -hex 32');
      process.exit(1);
    }
    return process.env.DB_ENCRYPTION_KEY;
  }

  const keyFile = path.join(dataDir, 'encryption.key');
  mkdirSync(dataDir, { recursive: true });

  if (existsSync(keyFile)) {
    const key = readFileSync(keyFile, 'utf8').trim();
    if (key.length >= 32) {
      encryptionKeyAutoGenerated = true;
      return key;
    }
    // File too short — regenerate
    console.warn('[WARN] encryption.key file is too short — regenerating');
  }

  const key = crypto.randomBytes(32).toString('hex'); // 64 hex chars
  writeFileSync(keyFile, key, { mode: 0o600, encoding: 'utf8' });
  encryptionKeyAutoGenerated = true;
  return key;
}

// ─── Session secret — load from file or generate once ────────────────────
// If SESSION_SECRET env var is set it takes precedence (backward-compat).
// Otherwise we persist a 64-byte hex secret in DATA_DIR/session.secret.
// The file is created with mode 0o600 (owner-read-only).
function resolveSessionSecret() {
  if (process.env.SESSION_SECRET) {
    if (process.env.SESSION_SECRET.length < 32) {
      console.error('FATAL: SESSION_SECRET env var must be at least 32 characters.');
      process.exit(1);
    }
    return process.env.SESSION_SECRET;
  }

  const secretFile = path.join(dataDir, 'session.secret');
  if (existsSync(secretFile)) {
    const secret = readFileSync(secretFile, 'utf8').trim();
    if (secret.length >= 64) return secret;
    // File exists but is too short — regenerate
    console.warn('session.secret file is too short — regenerating');
  }

  mkdirSync(dataDir, { recursive: true });
  const secret = crypto.randomBytes(64).toString('hex'); // 128 hex chars
  writeFileSync(secretFile, secret, { mode: 0o600, encoding: 'utf8' });
  console.log(`Generated session secret → ${secretFile}`);
  return secret;
}

// ─── No required env vars — everything has a safe fallback ───────────────
const dbEncryptionKey = resolveEncryptionKey();
const sessionSecret = resolveSessionSecret();

// Loud startup warning when using an auto-generated encryption key
if (encryptionKeyAutoGenerated) {
  const line = '═'.repeat(70);
  console.warn(`\n\x1b[41m\x1b[1m ${line} \x1b[0m`);
  console.warn(`\x1b[41m\x1b[1m  ⚠  WARNING: DB_ENCRYPTION_KEY is not set — using auto-generated key  \x1b[0m`);
  console.warn(`\x1b[41m\x1b[1m  Key stored at: ${path.join(dataDir, 'encryption.key')}  \x1b[0m`);
  console.warn(`\x1b[41m\x1b[1m  Back up this file. If lost, your encrypted vault is unrecoverable.  \x1b[0m`);
  console.warn(`\x1b[41m\x1b[1m ${line} \x1b[0m\n`);
}

const config = Object.freeze({
  version,
  repoUrl: 'https://github.com/kotoxie/deadman',
  port: parseInt(process.env.PORT || '6680', 10),
  logLevel: process.env.LOG_LEVEL || 'info',
  dataDir,
  sessionSecret,
  dbEncryptionKey,
  encryptionKeyAutoGenerated,
  tlsCertPath: process.env.TLS_CERT_PATH || null,
  tlsKeyPath:  process.env.TLS_KEY_PATH  || null,
});

export default config;
